name: CI Pipeline

on:
  push:
    branches:
      - development
      - feature/*
  pull_request:
    branches:
      - main
      - development

jobs:
  backend-build:
    runs-on: ubuntu-latest
    name: Backend Build and Test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js for Backend
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm install

      - name: Run Backend Tests
        working-directory: ./backend
        run: npm test

  frontend-build:
    runs-on: ubuntu-latest
    name: Frontend Build and Test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js for Frontend
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm install

      - name: Run Frontend Tests
        working-directory: ./frontend
        run: npm test
